---
- hosts: 
  tasks:
  - name: Generate new password
    run_once: true
    shell: "head /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 15 ; echo ''"
    register: new_pass

- hosts: 
  tasks:
  - name: Change password
    become: yes
    user:
      name: oddconcepts
      password: "{{ hostvars['localhost'].new_pass.stdout | password_hash('sha512') }}"

- hosts: 
  tasks:
  - name: Update K8S secret
    become_user: kube
    become: yes
    shell: |
      "/home/kube/script/geofront-mgr.py secret REMOTE {{ hostvars['localhost'].new_pass.stdout }}"
      "/home/kube/script/geofront-mgr.py restart"
