---
- hosts: 
  vars_prompt:
    - name: "pw"
      prompt: "Enter new password"
    - name: "pw_chk"
      prompt: "Enter new password again:"
  tasks:
    - name: "Change password"
      become: yes
      user:
        name: oddconcepts
        password: "{{ pw | password_hash('sha512') }}"
      when: pw == pw_chk
