---
- hosts: 
  become: yes
  tasks:
  - name: Get disk list except os disk (sda)
    shell: sudo fdisk -l |egrep '/dev/sd|/dev/nvme' |egrep -v 'sda' |grep ':' |cut -d':' -f1 |cut -d'/' -f3 |sort
    register: disk_list

  - name: Partitioning disk
    parted:
      device: "/dev/{{ item }}"
      number: 1
      state: present
      label: gpt
    with_items:
      - "{{ disk_list.stdout_lines }}"

  - name: Get partition list except os disk (sda)
    shell: sudo fdisk -l |egrep '/dev/sd|/dev/nvme' |egrep -v 'sda' |grep ':' |cut -d':' -f1 |cut -d'/' -f3 |sort
    register: disk_part_list
  
  - name: Create Filesystem
    filesystem:
      fstype: ext4
      dev: "/dev/{{ item }}"
    with_items:
      - "{{ disk_part_list.stdout_lines }}"
