---
- hosts: 
  become: yes
  tasks:
    - name: apt-get update
      apt:
        update_cache: yes

    - name: Install pre-requirement packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - apt-transport-https
        - curl
        - wget
        - htop
        - iotop
        - sysstat
        
    - name: add apt-key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: add elasticsearch repo
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
        filename: elastic-7.x.list

    - name: apt-get update
      apt:
        update_cache: yes

    - name: install filebeat
      apt:
        name: filebeat=7.9.2

    - name: enable filebeat
      service:
        name: filebeat
        enabled: yes
