---
- hosts: 
  tasks:
    - name: Create cluster join token
      become: yes
      become_user: kube
      command: kubeadm token create --print-join-command
      register: join_command
    - name: Create cluster join script
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
