---
- hosts: es 
#  become: yes
  vars_files:
    - ../vars/vault.yml
    - ../vars/oc-vars.yml
  tasks:
    - name: Get system uptime
      shell: uptime |awk '{print $3,$4}' 
      register: res
    - debug:
        var: res.stdout_lines
